### ISSUE TITLE
Adding trustline fails silently

### ISSUE THREAD

**Issue by chevdor** [johansten/stargazer#17]
No error, but coming back to the screen, the previously added anchors are gone.

**Comment by johansten** [comment]
I just noticed it myself. Found the problem, will release a new version.

**Comment by johansten** [comment]
Fixed in 29ed5e42

**Comment by chevdor** [comment]
I tested the new build and I still see the issue:
![out](https://cloud.githubusercontent.com/assets/738724/26146855/ec417042-3af1-11e7-94f6-a96384d3d5db.gif)

**Comment by johansten** [comment]
Gotcha.. you should have gotten an error message there, you need a balance
to be able to add anchors. Each anchor is 10 xlm on top of the 20 to
activate the account.
